import type { NextPage } from 'next'
import Head from 'next/head'
import { useAccount, useContractRead } from 'wagmi'
import { Header } from '../components/Header'
import * as presentMaterialsCurator from "../contractABI/presentMaterialsCurator.json"
import EditionCard from '../components/EditionCard';

const Home: NextPage = () => {

  // get account hook
  const { address, connector, isConnecting, isConnected, status} = useAccount(); 
  const currentUserAddress = address ? address : ""

  // CuratorContract Read Call --> query array of all active curators
  const { data, isError, isLoading, isSuccess, isFetching  } = useContractRead({
    addressOrName: "0xE5D36DF3087C19f108BBA4bb0D79143b8b4725Bb", // PresentMaterialsCurator https://rinkeby.etherscan.io/address/0xe5d36df3087c19f108bba4bb0d79143b8b4725bb#writeContract
    contractInterface: presentMaterialsCurator.abi,
    functionName: 'viewAllCollections',
    watch: true,
    onError(error) {
        console.log("error: ", isError)
    },
    onSuccess(data) {
        console.log("Array of current collections --> ", data)
    }  
  })
  
  const collectionData = data ? data : []

  return (
    <div className='flex flex-col justify-center h-full min-h-screen' >
      <Head>
        <title>Present Materials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className=" border-white border-solid text-white grid  grid-rows-3 sm:grid-cols-3 h-fit ">        

      {
        collectionData.map((collection, index) => {
          while (index < collectionData.length) {
            return (
              <EditionCard editionAddress={collectionData[index]} />
            )
          }
        })
      }

      </main>
    </div>
  )
}

export default Home
